image: timbru31/java-node:11-azul-alpine-jdk

stages:
  - QA
  - deploy

validateHTML:
  stage: QA
  script:
    - npm install
    - npm run validate-html

sonar:
  stage: QA
  script:
    - npm install
    - npm run validate-sonar-ci

deploy:
  stage: deploy
  only:
    - main
  except:
    changes:
      - documents/**/*
  script:
    - apk add openssh-client
    - apk add --update nodejs npm
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - pwd
    - rm src/config.json
    - ssh-keyscan -H 172.18.18.200 >> ~/.ssh/known_hosts
    - mkdir client-06
    - scp -qr ./* gitlab-runner@172.18.18.200:"./client-06/"
    - cd ./client-06/
    - npm install
    - npm run build
    - cp -r ./dist/* gitlab-runner@172.18.18.200:"/var/www/html/2022-2023/mars-06/"
  environment: production